version: '3.7'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql-server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrongPassword123"
      ACCEPT_EULA: "Y"  
    volumes:
      - mssql-data:/var/opt/mssql


  my_spark:
    image: jupyter/pyspark-notebook:latest
    user: root
    environment:
      - SPARK_HOME=/usr/local/spark
      - PYSPARK_SUBMIT_ARGS=--driver-class-path /app/mssql-jdbc-12.6.1.jre8.jar pyspark-shell
    ports:
      - "8888:8888" # Port dla Jupyter
      - "8501:8501" # Dodatkowy port dla Streamlit
    command: start-notebook.sh --NotebookApp.token=''
    volumes:
      - ./mssql-jdbc-12.6.1.jre8.jar:/app/mssql-jdbc-12.6.1.jre8.jar
      - .:/home/jovyan  # Mapowanie całego aktualnego katalogu do kontenera
      - ./init.sql:/app/init.sql


volumes:
  mssql-data:
    driver: local
